test_that("boilerplate text is inserted", {
  withr::with_tempdir({
    add_manuscript(manuscript = "apa6")
    lnz <- readLines("manuscript/manuscript.Rmd")
    expect_true(any(grepl("Workflow for Open Reproducible Code in Science", lnz, fixed = TRUE)))
    expect_true(any(grepl("load_data()", lnz, fixed = TRUE)))
    file.remove("manuscript/manuscript.Rmd")
    add_manuscript(manuscript = "github_document")
    lnz <- readLines("manuscript/manuscript.Rmd")
    expect_true(any(grepl("Workflow for Open Reproducible Code in Science", lnz, fixed = TRUE)))
    expect_true(any(grepl("load_data()", lnz, fixed = TRUE)))
    file.remove("manuscript/manuscript.Rmd")
    add_manuscript(manuscript = "acm_article")
    lnz <- readLines("manuscript/manuscript.Rmd")
    expect_true(any(grepl("Workflow for Open Reproducible Code in Science", lnz, fixed = TRUE)))
    expect_true(any(grepl("load_data()", lnz, fixed = TRUE)))
    file.remove("manuscript/manuscript.Rmd")
    add_manuscript(manuscript = "target_markdown")
    lnz <- readLines("manuscript/manuscript.Rmd")
    expect_true(any(grepl("Workflow for Open Reproducible Code in Science", lnz, fixed = TRUE)))
    expect_true(any(grepl("load_data()", lnz, fixed = TRUE)))
    file.remove("manuscript/manuscript.Rmd")
  })
})


test_that("boilerplate text is inserted", {
  withr::with_tempdir({
    add_manuscript(manuscript = "target_markdown")
    print(list.files())
    # lnz <- readLines("manuscript.Rmd")
    # print(lnz)
    #expect_true(any(grepl("Workflow for Open Reproducible Code in Science", lnz, fixed = TRUE)))
    #expect_true(any(grepl("load_data()", lnz, fixed = TRUE)))
  })
})
