expect_error({ synthetic(Indometh) }, NA)
expect_error({ synthetic(InsectSprays) }, NA)
expect_error({ synthetic(LifeCycleSavings) }, NA)
expect_error({ synthetic(Loblolly) }, NA)
expect_error({ synthetic(Orange) }, NA)
expect_error({ synthetic(OrchardSprays) }, NA)
expect_error({ synthetic(PlantGrowth) }, NA)
expect_error({ synthetic(Puromycin) }, NA)
expect_error({ synthetic(Theoph) }, NA)
expect_error({ synthetic(data.frame(Titanic)) }, NA)
expect_error({ synthetic(ToothGrowth) }, NA)
expect_error({ synthetic(data.frame(UCBAdmissions)) }, NA)
expect_error({ synthetic(USArrests) }, NA)
expect_error({ synthetic(USJudgeRatings) }, NA)
expect_error({ synthetic(data.frame(USPersonalExpenditure)) }, NA)
expect_error({ synthetic(data.frame(VADeaths)) }, NA)
expect_error({ synthetic(data.frame(WorldPhones)) }, NA)
expect_error({ synthetic(data.frame(ability.cov$cov)) }, NA)

expect_error({ synthetic(airquality) }, NA)

expect_error({ synthetic(anscombe) }, NA)
expect_error({ synthetic(attenu) }, NA)
expect_error({ synthetic(attitude) }, NA)

expect_error({ synthetic(beaver1) }, NA)
expect_error({ synthetic(beaver2) }, NA)
expect_error({ synthetic(cars) }, NA)
expect_error({ synthetic(chickwts) }, NA)

expect_error({ synthetic(data.frame(crimtab)) }, NA)

expect_error({ synthetic(esoph) }, NA)
expect_error({ synthetic(data.frame(euro.cross)) }, NA)

expect_error({ synthetic(faithful) }, NA)

expect_error({ synthetic(freeny) }, NA)
expect_error({ synthetic(data.frame(freeny.x)) }, NA)
# Check what happens in case of 1D data
expect_error({ synthetic(data.frame(freeny.y)) }, NA)
expect_error({ synthetic(infert) }, NA)
expect_error({ synthetic(iris) }, NA)
expect_error({ synthetic(iris3) })
expect_error({ synthetic(islands) })
expect_error({ synthetic(ldeaths) })
expect_error({ synthetic(lh) })
expect_error({ synthetic(longley) }, NA)
expect_error({ synthetic(lynx) })
expect_error({ synthetic(mdeaths) })
expect_error({ synthetic(morley) }, NA)
expect_error({ synthetic(mtcars) }, NA)
expect_error({ synthetic(nhtemp) })
expect_error({ synthetic(nottem) })
expect_error({ synthetic(npk) }, NA)
expect_error({ synthetic(occupationalStatus) })
expect_error({ synthetic(precip) })
expect_error({ synthetic(presidents) })
expect_error({ synthetic(pressure) }, NA)
expect_error({ synthetic(quakes) }, NA)
expect_error({ synthetic(randu) }, NA)
expect_error({ synthetic(rivers) })
expect_error({ synthetic(rock) }, NA)
expect_error({ synthetic(sleep) }, NA)
expect_error({ synthetic(stack.loss) })
expect_error({ synthetic(stack.x) }, NA)
expect_error({ synthetic(stackloss) }, NA)
expect_error({ synthetic(state.abb) })
expect_error({ synthetic(state.area) })
expect_error({ synthetic(state.center) })
expect_error({ synthetic(state.division) })
expect_error({ synthetic(state.name) })
expect_error({ synthetic(state.region) })
expect_error({ synthetic(data.frame(state.x77)) }, NA)

expect_error({ synthetic(swiss) }, NA)

expect_error({ synthetic(trees) }, NA)

expect_error({ synthetic(data.frame(volcano)) }, NA)
expect_error({ synthetic(warpbreaks) }, NA)
expect_error({ synthetic(women) }, NA)
